data_root_directory: /sise/assafzar-group/assafzar/metalspy/TNBC-metals-data
experiments_root_dir_results: ./results
hist_size: 20
exclude_outlier_cores: False
metal: iron
percentile: 0.8
seed: 11
model_seed: 11
